POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/0381bca5-06bb-43ab-8e81-7ce163767e39/attendees
Content-Type: application/json

{
  "name": "Joedison Dias",
  "email": "emaildojoedison2@gmail.com"
}

###

GET http://localhost:3333/events/0381bca5-06bb-43ab-8e81-7ce163767e39