POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/4acbd818-2a62-4eb2-be51-ea993c075931/attendees
Content-Type: application/json

{
  "name": "Joedison Dias",
  "email": "emaildojoedison@gmail.com"
}